authorName: liyuan
experimentName: hier_dgi_nci1
trialConcurrency: 4
maxExecDuration: 4h
maxTrialNum: 200
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python3 run.py --dataset NCI1
  codeDir: .
  gpuNum: 1
localConfig:
  gpuIndices: 0,1,2,3
  useActiveGpu: false