authorName: liyuan
experimentName: hier_dgi_mutagenicity
trialConcurrency: 18
maxExecDuration: 6h
maxTrialNum: 600
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trial:
  command: python3 run.py --dataset Mutagenicity
  codeDir: .
  gpuNum: 1
localConfig:
  gpuIndices: 2,3,4,5,6,7
  maxTrialNumPerGpu: 3
  useActiveGpu: true